### ISSUE TITLE
There should be a flattening conversion from Result<T> to Maybe<T>

### ISSUE THREAD

**Issue by Insomniak47** [wareismymind/Secundatives#18]
Given that a Result<T> is just a superset of Maybe<T> with augmenting error data in the None case there should be a one way conversion from a Result<T> to a Maybe<T>.

I'm not sure what that would look like. I don't like the idea that it would be implicit but I can't think of a great word for it. Unfortunately it conflicts a bit with AsMaybe<T> conceptually and since we can't make Result<T> a struct safely (thanks C#) and we can't specialize the generic we're sort of stuck in a relatively confusing space.

@slagroom input?

**Comment by Insomniak47** [comment]
I just took a look at the rust implementation and it looks like they use 

"ok" as Result<T,E> -> Maybe<T> and 
"error" as Result<T,E> -> Maybe<E>

**Comment by slagroom** [comment]
Explicit cast with a `Maybe<T>(Result<T> r)` ctor seems fine to me. I can't think of case where I'm getting a Result and need a Maybe to do what I want (IsValue vs Exists). The only reason I'm thinking would be to forward a Result to a thing that wants a Maybe in which case being explicit sounds right anyway.
